name: Ozonetel AI Software Development Toolkit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # You can adjust this to '3.9', '3.8', etc. as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build binary wheel and a source tarball
        run: python setup.py sdist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          password: ${{ secrets.secret_ozonetelaisdk }}
          repository_url: https://upload.pypi.org/legacy/

      # - name: Run tests
      #  run: |
      #    pytest
